# -*- coding: utf-8 -*-
"""Ejercicios_Eduar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGUjYJRo1VlyO26F4qDG3DZXwBq_MRU_
"""

from google.colab import drive
drive.mount('/content/drive')

ruta='/content/drive/Othercomputers/ThinkPad/Desktop/Eduar/'

import pandas as pd
import os

os.listdir(ruta)[0]

df=pd.read_csv(ruta+os.listdir(ruta)[0])

df['direction'].value_counts()

df

df['ruta']=df['origin']+'-'+df['destination']

df.head()

"""# Opcion 1"""

df_op1=df['ruta'].value_counts().head(10)
df_op1

df_op1.to_csv(ruta+'opcion1.csv')

ruta+'opcion1.csv'

"""# Opcion 2"""

df_op2=df.groupby(by='transport_mode')['total_value'].agg(['sum','mean']).round(2)
df_op2

df_op2.to_csv(ruta+'opcion2.csv')

"""# Opcion 3"""

df['total_value'].hist()

q_value=df['total_value'].quantile(0.8)

df2=df[df['total_value']<=q_value]
df2

df2['ruta'].value_counts()

ls_origin=df2['origin'].value_counts().index.to_list()

ls_destination=df2['destination'].value_counts().index.to_list()

df_op3=pd.DataFrame(list(set(ls_origin+ls_destination)), columns=['paises'])
df_op3

df_op3.to_csv(ruta+'opcion3.csv')